name: Build E2E Matrix
description: Build and output a custom matrix for E2E tests.

outputs:
  matrix:
    description: Parameterized matrix in JSON format
    value: ${{ steps.matrix.outputs.result }}

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      id: matrix
      with:
        script: | # js
          const java = 11;

          const defaultRunner = "ubuntu-22.04";

          const defaultOptions = {
            "java-version": java,
            runner: defaultRunner,
            edition: "ee",
            context: "folder"
          };

          const testSets = [

            ["question", {containers: [1,2,3]} ],

          ];

          const config = testSets.map(([name, specialOptions]) => {
            return {
              ...defaultOptions,
              ...specialOptions,
              name,
            }
          });

          const matrix = { include: config };
          return matrix;
